### ISSUE TITLE
To-dos

### ISSUE THREAD

**Issue by tungpatrick** [UBC-MDS/CleanR#14]
- [x] Everyone should finalize documentation (and copy it onto the README)
- [x] @phuntsoktseten  please add to the "Usage" section on the README
- [x] CHECK COVERAGE!! Write more tests and fix function to make 100% branch coverage!
- [x] REMEMBER TO DO THIS FOR BOTH PYTHON AND R!!!
- [x] Add a vignette for your own function in R (http://stat545.com/packages05_foofactors-package-02.html#add-a-vignette)

**Comment by heathervant** [comment]
note: how to check for coverage in console:
```coverage run -m --branch pytest -q; coverage report -m; coverage html```
